### ISSUE TITLE
Problem while updating a maven project

### ISSUE THREAD

**Issue by teohaik** [istlab/Alitheia-Core#4]
I get an error while trying to update a module via  maven->update project 

An internal error occurred during: "Updating Maven Project".
Unsupported IClasspathEntry kind=4

![maven_problem](https://f.cloud.github.com/assets/1785012/1164318/73c13f6a-2053-11e3-80e5-b7fec617e882.png)

**Comment by gousiosg** [comment]
Why is this a problem with Alitheia Core?

**Comment by gousiosg** [comment]
No response, therefore closing

**Comment by gousiosg** [comment]
Upon further experimentation, it turns out that you do not need the Eclipse Maven Plug-in to import Alitheia Core. You can just do `mvn eclipse:eclipse` on the command line, then Import -> Existing Projects into Workspace in Eclipse, set the Alitheia Core checkout directory as the root directory (also set import nested projects), import everything. All projects will be marked as failed compilation because the M2_REPO variable is not set in Eclipse. You can set this manually as per this reply on StackOverflow:

http://stackoverflow.com/questions/13734832/unbound-classpath-variable-junit-and-log4j-when-importing-a-libgdx-project-in-to
